# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tmolinar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/17 15:30:17 by tmolinar          #+#    #+#              #
#    Updated: 2018/09/17 15:30:19 by tmolinar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = doop

all: $(NAME)

$(NAME):
	gcc -Wall -Werror -Wextra *.c -o ft_advanced_do-op

clean:
	/bin/rm -f ft_advanced_do-op

re: clean all
